services:
  eaglai:
    build:
      context: ./backend
    container_name: eaglai
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EAGLAI_PORT=${EAGLAI_PORT}
      - OLLAMA_URL=http://ollama-mock:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - CORS_ALLOWED_ORIGIN=${FRONTEND_URL}
    ports:
      - ${EAGLAI_PORT}:${EAGLAI_PORT}
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "eaglai-backend"
      tsdproxy.port: ${EAGLAI_PORT}

  frontend:
    build:
      context: ./frontend
    container_name: eaglai-frontend
    restart: unless-stopped
    depends_on:
      - eaglai
    environment:
      - VITE_API_URL=${BACKEND_URL}/api/v1
    ports:
      - 3001:80
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "eaglai"

  db:
    image: postgres:16.2
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  ollama-mock:
    build:
      context: ./mocks/ollama
    container_name: ollama-mock
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}

  db-cleaner:
    image: alpine:3.20
    container_name: db-cleaner
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./mocks/clean-db.sh:/clean-db.sh:ro
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache postgresql-client busybox-suid && while [ ! -f /clean-db.sh ]; do sleep 1; done && echo 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n0 * * * * /clean-db.sh' > /etc/crontabs/root && crond -f -d 8"]

volumes:
  ollama_models:
  db_data:
