services:
  eaglai:
    build:
      context: ./backend
    container_name: eaglai
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EAGLAI_PORT=${EAGLAI_PORT}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - CORS_ALLOWED_ORIGIN=${FRONTEND_URL}
    ports:
      - ${EAGLAI_PORT}:${EAGLAI_PORT}

  frontend:
    build:
      context: ./frontend
    container_name: eaglai-frontend
    restart: unless-stopped
    depends_on:
      - eaglai
    environment:
      - VITE_API_URL=${BACKEND_URL}/api/v1
    ports:
      - 3000:80

  db:
    image: postgres:16.2
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:0.9.5
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_models:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    ports:
      - 11434:11434
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    tty: true
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_models:
  db_data:
