services:
  eaglai:
    build:
      context: ./backend
    container_name: eaglai
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${SPRING_USER}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EAGLAI_PORT=${EAGLAI_PORT}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
    ports:
      - ${EAGLAI_PORT}:${EAGLAI_PORT}

  frontend:
    build:
      context: ./frontend
    container_name: eaglai-frontend
    depends_on:
      - eaglai
    environment:
      - VITE_API_URL=http://localhost:${EAGLAI_PORT}/api/v1
    ports:
      - 3000:80

  db:
    image: postgres:16.2
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  ollama:
    image: ollama/ollama:0.9.5
    container_name: ollama
    volumes:
      - ./data/ollama:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    ports:
      - 11434:11434
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    tty: true
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]